In [1]:
import pandas as pd 
import numpy as np 

In [3]:
df=pd.read_csv(r'C:\Users\raosa\Desktop\eda\files\spam.csv')

In [5]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.groupby('Category').describe(include='all')

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [12]:
#convertin spam 1 and non spam 0 
df['spam']=df.Category.apply(lambda x:1 if x=='spam' else 0)

In [15]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

## countvectorizer 

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
values=df.Message
values.sample(5)

2584                Goodmorning, today i am late for 1hr.
2972    Height of Confidence: All the Aeronautics prof...
4317    I can't speak, bcaz mobile have problem. I can...
4745                                   Thinking of u ;) x
2818    Gr8 Poly tones 4 ALL mobs direct 2u rply with ...
Name: Message, dtype: object

In [36]:
values=list(values)

In [37]:
vector=CountVectorizer()

In [42]:
X=vector.fit_transform(values)

In [58]:
vectorvalues=(vector.get_feature_names_out()) #same as feature_names but latest 
print(type(vectorvalues))
vectorvalues=np.array(vectorvalues)
print(vectorvalues.shape)
print(vectorvalues[:3])

<class 'numpy.ndarray'>
(8709,)
['00' '000' '000pes']


In [61]:
print(X.toarray()) #the array or the dummies matrix of each word in vectorvalues

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [63]:
matrix=X.toarray()
print(vectorvalues.shape)
matrix.shape


(8709,)


(5572, 8709)

### continuing the spam

In [64]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.25)

In [69]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_count=v.fit_transform(X_train,y_train)
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [70]:
from sklearn.naive_bayes import MultinomialNB #cause its discrete but not binary

In [72]:
model=MultinomialNB()
model.fit(X_train_count,y_train) #occurance of each word again spam and not spam

MultinomialNB()

In [75]:
X_test_count=v.transform(X_test)
score=model.score(X_test_count,y_test) #score 
score

0.9834888729361091

In [80]:
y_pred=model.predict(X_test_count)
y_pred


array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

## using pipeline 
#pipeline helps us to reduce the steps taken 

In [81]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ("vector",CountVectorizer()),
    ('modell',MultinomialNB())
]) #when ever we now use clf it will do both this 2 steps 

In [83]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vector', CountVectorizer()), ('modell', MultinomialNB())])

In [84]:
clf.score(X_test,y_test)

0.9834888729361091

In [85]:
y_predd=clf.predict(X_test)